spring: 
    application: 
        name: inspire-spring
    
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/inspire
        username: root
        password: 1234

# mybatis config
mybatis:
  mapper-locations:
  - /mappers/**/*Mapper.xml

server: 
    port: 8088
