spring:
  application:
    name: application.name=inspire-restspring

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/inspire
    username: root
    password: 1234
    
    
server:
    port: 8088
    
    
mybatis:
  mapper-locations:
  - /mappers/**/*Mapper.xml
  config-location: classpath:/config/blog/mybatis-config.xml