spring:
  application:
    name: application.name=inspire-restjpa

    # maria db
  datasource:
    driver-class-name: ${DRIVER}
    url: ${URL}
    username: ${USER}
    password: ${PASSWD}
    
    # h2 db
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   # url: jdbc:h2:mem:inspire
  #   url: jdbc:h2:file:./data/inspire;AUTO_SERVER=TRUE
  #   username: root
  #   password: 

  jpa:
    hibernate:
    # create, create-drop, update, none
      ddl-auto: none
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:

        # h2
        # dialect: org.hibernate.dialect.H2Dialect
        
        # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8088/h2-console
    
    
    
server:
  port: 8088
  
jwt:
  secret: ${JWT_SECRET_KEY}
    
    
# mybatis:
#   mapper-locations:
#   - /mappers/**/*Mapper.xml
#   config-location: classpath:/config/blog/mybatis-config.xml

openApi:
  serviceKey: ${SERVICE_KEY}
  callBackUrl: ${CALLBACKURL}
  dataType: ${TYPE}